config/routes.rb
Rails.application.routes.draw do
  resources :notifications,only: :update
  get 'notifications/index'
  root 'users#top'
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #delete 'posts/:id' => 'posts#destroy' 
  resources :posts do
  get 'posts/:id' => 'posts#show',as: 'post'
  patch 'posts/:id' => 'posts#update'
    resources :participants, :only => [:create, :destroy]
    delete 'cancel' => 'participants#cancel'
    resources :likes, :only=> [:index, :create, :destroy]
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #devise_for :users, controllers: { registrations: 'users/registrations' }
  get "users/:id/introduce" => "users#introduce"
  get "users/:id/records" => "users#records",as: 'records'
  get "users/:id/likes" => "users#likes",as: 'likes'
  get "users/:id/participants" => "users#participants",as: 'participants'
  #nnget 'registrations/:id/edit' => 'registrations#edit', as:'edit_registrations'
end

app/models/notification.rb
class Notification < ApplicationRecord
    default_scope -> { order(created_at: :desc)}

    belongs_to :room, optional: true
    belongs_to :message, optional: true

    belongs_to :visitor, class_name: 'User',foreign_key: 'visitor_id', optional: true
    belongs_to :visited, class_name: 'User',foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
      @notifications = current_user.passive_notifications
    end

    def update
      notification=Notification.find(params[:id]) #...①
      if notification.update(checked: true) #...②
        redirect_to action: :index
      end
    end
  end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% if notification.checked == false %>
    <div class="notification">
    <% visitor = notification.visitor %>
    <% visited = notification.visited %>
    <ul class="listgroup">
    <li class="listgroup-item">
    <% @currentUserEntry=Entry.where(user_id: current_user.id) %>
    <%  @userEntry=Entry.where(user_id: visitor.id) %>
        <% @currentUserEntry.each do |cu|%>
            <% @userEntry.each do |u| %>
            <% if cu.room_id == u.room_id then %>
                <% @roomId = cu.room_id %>
            <% end %>
            <% end %>
    <% end %>

        <div class="notification-content">
        <%= notification.created_at.in_time_zone('Tokyo') %>
        <div class="notification-name">
        
        <%= link_to room_path(@roomId),class: "notification-link" do %>
            <%= visitor.name %>さん
        <% end %>
        <% if notification.action=='dm' %>
        があなたにDMを送りました
        <% end %>
        </div>

        <%= button_to '削除',notification_path(notification.id),method: :put,class:"notification-btn" %>
        </div>
    </li>
    
    </ul>
    </div>
<% end %>

app/views/notifications/index.html.erb
<div class="mypage-header">
<div class="mypage-link-area">
<ul>
    <li><a href="/users/current_user/records">投稿記録</a></li>
    <li><%= link_to "参加申込記録", participants_path(current_user) %></li>
    <li><%= link_to "お気に入り", likes_path(current_user) %></li>
    <li><%= link_to "DM通知",  notifications_index_path(current_user) %></li>
    <li><%= link_to "ユーザー情報編集",edit_user_registration_path(current_user)%></li>
    <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
</ul>
</div>
</div>

<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
<% if notifications.exists? %>
    <%= render notifications %>
<% else %>
<div class="notification-content notification">
<p>通知はありません</p>
</div>
<% end %>