config/routes.rb
Rails.application.routes.draw do
  resources :notifications,only: :update
  get 'notifications/index'
  root 'users#top'
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #delete 'posts/:id' => 'posts#destroy' 
  resources :posts do
  get 'posts/:id' => 'posts#show',as: 'post'
  patch 'posts/:id' => 'posts#update'
    resources :participants, :only => [:create, :destroy]
    delete 'cancel' => 'participants#cancel'
    resources :likes, :only=> [:index, :create, :destroy]
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  #devise_for :users, controllers: { registrations: 'users/registrations' }
  get "users/:id/introduce" => "users#introduce"
  get "users/:id/records" => "users#records",as: 'records'
  get "users/:id/likes" => "users#likes",as: 'likes'
  get "users/:id/participants" => "users#participants",as: 'participants'
  #nnget 'registrations/:id/edit' => 'registrations#edit', as:'edit_registrations'
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :participants, dependent: :destroy
    has_many :participated_users, through: :participants, source: :user
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :notifications, dependent: :destroy
  
  def create_notification_patricipant!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'participant'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'participant'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @search = Post.search(params[:q]) # この行を追加
        @posts = @search.result #この行を修正
    
        respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @posts }
                #if params[:search] != nil && params[:search] != ''
                #部分検索かつ複数検索
                #@posts = Post.where("location LIKE ? ", "%" + params[:search] + "%").or(Post.where("date LIKE ? ", "%" + params[:search] + "%"))
                #else
                #@posts = Post.all
                end
        end
    #@posts = Post.all
    

def new 
    @post=Post.new
end

def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
        redirect_to :action => "index"
    else
        redirect_to :action => "new"
    end
end

def show
    @post = Post.find(params[:id])
    @participant = Participant.new
    @like = Like.new
end

def records
    @list = Post.where(user: current_user)
end

def edit
    @post = Post.find(params[:id])
end

    def  update
        @post = Post.find(params[:id])
        if @post.update(post_params)
        redirect_to :action => "show", :id => @post.id
        else
        redirect_to :action => "new"
        end
    end

    def destroy
        Post.find(params[:id]).destroy
    redirect_to action: :index
    end

    def address

    end

def map
            results = Geocoder.search(params[:location])
            @latlng = results.first.coordinates
            # これでmap.js.erbで、経度緯度情報が入った@latlngを使える。
        
            respond_to do |format|
            format.js
end

end

before_action :authenticate_user!

private
def post_params
    params.require(:post).permit(:body,:title,:date,:capacity,:location,:remarks,:explanation)
end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb


    <div class="post-container">
    <h5 class="title"><i class="far fa-comment-dots"></i> <i class="fas fa-envelope"></i> <i class="far fa-comment-dots"></i></h5>
    <%= form_for(@post, :url => { controller:'posts', action:'update'})do |f| %>
    <div class="postform">
        <%= f.label :タイトル %>
        
        <%= f.text_field :title,size: 75, class:"form" %>
    </div>

    <div class="a1">
    <div class="postform">
        <%= f.label :募集人数 %><br>
        <%= f.number_field :capacity,size: 5, class:"form a2" %>
    </div>
    <div class="postform">
        <%= f.label :開催日時 %><br>
        <%= f.datetime_field :date,size: 30, class:"form a2" %>
    </div>
    </div>
        
    <div class="postform">
        <%= f.label :開催場所 %><br>
        <%= f.text_field :location,size: 40, class:"form" %>
    </div>
        
    <div class="postform"><br>
        <%= f.label :募集対象 %><br>
        <%= f.text_field :remarks,size: 40, class:"form" %>
    </div>
        
    <div class="postform">
        <%= f.label :詳細説明 %>
        <br>   
        <%= f.text_area :explanation, size: "70×100", class:"form" %>
    </div>
        <br>
        <div class="submit-button">
        <input type="submit" value="編集" class="button">
        </div>
    
    <% end %>
</div>



app/views/posts/index.html.erb
    <div class="searchwithmap">
    <div class="search">
    <h3><i class="fas fa-search"></i></h3>
        <%= search_form_for @search do |f| %>
    <div class="search-all">
    <div class="search1">
    <%= f.label :location_cont, '場所 ' %>
    <%= f.text_field :location_cont, class:"search-area" %><br>
    </div>
    <div class="search2">
    <%= f.label :date_cont, '日時 ' %>
    <%= f.date_select :date_gteq, include_blank: true, class:"search-area"  %>〜
    <%= f.date_select :date_lteq, include_blank: true , class:"search-area" %>
    </div>
    </div>
    <div class="search-button">
        <%= f.submit '検索する' %>
    </div>
    <% end %>
    </div>
    
    <div class="maparea">
    <div id='map'></div>
<script>
let map
let marker = []; // マーカーを複数表示させたいので、配列化
function initMap(){
    map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 35.6585, lng: 139.7486},
        zoom: 6,
    });
    <% @posts.each do |place| %>
        <% results=Geocoder.search(place.location) %>
        <% if results.present? %>
        <% @latlng=results.first.coordinates %>
    (function(){
        var contentString = '場所：<%= link_to place.location,post_path(place.id) %>';
        var infowindow = new google.maps.InfoWindow({
        position:{lat: <%= @latlng[0] %>, lng: <%= @latlng[1] %>},
        content: contentString
        });
        var marker = new google.maps.Marker({
            position:{lat: <%= @latlng[0] %>, lng: <%= @latlng[1] %>},
            map: map,
            title: contentString
        });
        marker.addListener('click', function() {
        infowindow.open(map, marker);
        });
        })();
        <% end %>
    <% end %>
    }
</script>
</div>
</div>   

<div class="line"></div>

</div>

<div class="card-group">
    <% @posts.order(id: "DESC").each do |t| %> 
        <div class="card" style="width:300px;height:300px;overflow:auto;">
                <div class="cardheader">
                    <i class="fas fa-chess-queen"></i>
                </div>
                <div class="card-body"> 
                    <h5 class="card-title"><%= t.title %><br>👍<%= t.participated_users.count %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= t.date %><br>場所：<%= t.location %></h6>
                    <a href="/posts/<%= t.id %>" class="card-link card-link1">詳細</a>
                    <% if user_signed_in? && current_user.id == t.user_id %>
                        <a href="/posts/<%= t.id %>/edit" class="card-link card-link2" style="margin: 10px auto 0px auto;">編集</a>
                    <% end %>
                </div>
        </div>
    <% end %>
</div>

app/views/posts/map.js.erb
    (function(){
    // 位置情報をもつ変数を用意
    let pos = new google.maps.LatLng(
    <%= @latlng[0] %>, //latitude
    <%= @latlng[1] %>  //longitude
    );

    mapInstance.setCenter(pos)
    let marker = new google.maps.Marker({
        map: mapInstance,
        position: pos
    });
    })()

app/views/posts/new.html.erb


<div class="post-container">
    <h5 class="title"><i class="fas fa-comment-dots"></i>  <i class="far fa-envelope"></i>  <i class="fas fa-comment-dots"></i></h5>
    <%= form_for(@post, :url => { controller:'posts', action:'create'})do |f| %>
    <div class="postform">
        <%= f.label :タイトル %>
        
        <%= f.text_field :title,size: 75, class:"form" %>
    </div>

    <div class="a1">
    <div class="postform">
        <%= f.label :募集人数 %><br>
        <%= f.number_field :capacity,size: 5, class:"form a2" %>
    </div>
    <div class="postform">
        <%= f.label :開催日時 %><br>
        <%= f.datetime_field :date,size: 30, class:"form a2" %>
    </div>
    </div>
        
    <div class="postform">
        <%= f.label :開催場所 %><br>
        <%= f.text_field :location,size: 40, class:"form" %>
    </div>
        
    <div class="postform"><br>
        <%= f.label :募集対象 %><br>
        <%= f.text_field :remarks,size: 40, class:"form" %>
    </div>
        
    <div class="postform">
        <%= f.label :詳細説明 %>
        <br>   
        <%= f.text_area :explanation, size: "70×100", class:"form" %>
    </div>
        <br>
        <div class="submit-button">
        <input type="submit" value="投稿" class="button">
        </div>
    
    <% end %>
</div>



app/views/posts/show.html.erb
<div class="post-card">
<div class="post">
    <div class="post-header">
    <div class="avatar1" style="top:0; border:3px solid #40BA8D; position:absolute; left:75%;">
    <% if @post.user.image_url == nil %>
        <i class="fas fa-question post-image"></i>
    <% else %>
        <%= image_tag @post.user.image_url,class: "profile-img1" %>
    <% end %>
    </div>
        <h3 class="post-header-text"><%= @post.title %></h3>
        <h4 class="post-header-text-1"><a  class="post-user" href="/users/<%= @post.user.id %>"><%= @post.user.name %>さん</a>の投稿</h4>
    
    <div class="post-user-edit">
        <% if user_signed_in? && current_user.id == @post.user_id %>
            <%= link_to "編集", edit_post_path(@post.id), class:"edit-button e1", width:"30%" %>
            <%= button_to "削除", post_path(@post.id), method: :delete, class:"edit-button e2", width:"30%",onclick: "btnalert()" %>
        <% end %>
    </div>

    <div class="post-user-edit2">
        <div class="post-like">
        <% if current_user.id != @post.user_id %>
            <% if current_user.already_liked?(@post) %>
                <%= button_to 'いいね取消', post_like_path(@post), method: :delete, class:"edit-button e3" %>
            <% else %>
                <%= button_to 'いいね', post_likes_path(@post), class:"edit-button e3" %>
            <% end %>
        </div>
        <% end %>
        

    <br>
        <% if current_user.id != @post.user_id %>   
            <% if current_user.already_participated?(@post) %>
                <%= button_to '参加取消', post_participant_path(@post), method: :delete, class:"edit-button e2 e3" %>
            <% else %>
                <%= button_to '参加', post_participants_path(@post), class:"edit-button e2 e3" %>
            <% end %>
        <% end %>
    </div>
</div>
</div>
    <div class="post-body">
    <div class="postshow1">開催日時</div>　<div class="postshow"><%= @post.date %></div>
    <div class="postshow1">開催場所</div>　<div class="postshow"><%= @post.location %></div>
    <div class="postshow1">募集対象</div>　<div class="postshow"><%= @post.remarks %></div>
    <div class="postshow1">詳細説明</div>　<br><div class="postshow"><%= simple_format(@post.explanation) %></div>
    <div class="postshow1">現在の参加人数／募集人数</div> <br>   <div class="postshow"><%= @post.participants.count %>／ <%= @post.capacity %>人</div>
    

</div>

<div class="postshow2">現在の参加者</div>
    <% @post.participated_users.each do |user| %>
    <div class="participant-delete">
        <div class="participatist"><li><a class="post-user" href="/users/<%= user.id %>"><%= user.name%>さん</a></li></div>
        <% if current_user.id == @post.user_id %>
            <%= button_to '取消', post_participant_path(@post.id,user.id), method: :delete,class:"delete-button" %>
        <% end %>
    </div>
    <% end %>
</div>

<script>
function btnalert() {
    window.alert('消去しますか？');
}
</script>